### ISSUE TITLE
Access GoldenLayout container in component

### ISSUE THREAD

**Issue by fin-ger** [EmbeddedEnterprises/ng6-golden-layout#10]
A component should be able to access the [`Container`](http://golden-layout.com/docs/Container.html) instance to which it is bound.

This will enable the component to set the title of the tab pane.

Alternatively only expose an API to the component to set the title.

**Comment by martin31821** [comment]
Related to #3

**Comment by martin31821** [comment]
Fixed by #12, injecting the container is already possible, documentation was added.
