### ISSUE TITLE
How to get component state ?

### ISSUE THREAD

**Issue by sumitdubey** [EmbeddedEnterprises/ng6-golden-layout#17]
When creating a component  using **createNewComponent** and passing a state, How to get the state back ?

`this.goldenLayoutService.createNewComponent(
      {
          componentName: 'app-test',
          component: testComponent
      },
      "App Test!",
      {
           id: this.id
      }
);`

**Comment by martin31821** [comment]
You need to inject the `GoldenLayoutComponentState` token into your Component, this will inject the state you passed to your component into the angular class.
