### ISSUE TITLE
GoldenLayoutService  childcomponent is always true ?

### ISSUE THREAD

**Issue by nitin-** [EmbeddedEnterprises/ng6-golden-layout#20]
` GoldenLayoutComponent.prototype.ngOnInit = function () {
        var _this = this;
        if (isDevMode())
            console.log("Init@" + (this.isChildWindow ? 'child' : 'root') + "!");
        var anyWin = (this.topWindow);
        if (!this.isChildWindow) {
            anyWin.__apprefs = [];
            anyWin.__injector = this.injector;
        }
        anyWin.__apprefs.push(this.appref);
...........
..........

` 

> because this.isChildWindow is true all the time   anyWin.__apprefs is undefined .

**Comment by martin31821** [comment]
Can you tell me something about your environment? 
Browser/Electron, Version, angular version, etc?

**Comment by nitin-** [comment]
it was my fault , I was using window.open (for linked in login ). And was on the child window throughout and hence window.opener object was there and as per the code written in GoldenLayoutService 
isChildWindow() {
        return !!window.opener;
    }
Above mentioned issue was occuring.

But Can you tell me why have you restricted GoldenLayout components in child window @martin31821 @sumitdubey

**Comment by martin31821** [comment]
This is required for multi window popouts and service synchronization to work.

**Comment by nitin-** [comment]
Thanks
