### ISSUE TITLE
How to use glEventHub in angular components 

### ISSUE THREAD

**Issue by shobanmr** [EmbeddedEnterprises/ng6-golden-layout#21]
It's possible to use glEventHub in Reactjs to manipulate tabs with regard design changes and other events as well, which I could not achieve in angular.

Reactjs Example:
```
let config={...}
var myLayout = new GoldenLayout( config );
  myLayout.registerComponent( 'Applications', Applications );
myLayout.init();


let event = this.props.glEventHub._layoutManager;
event.root.contentItems[0].contentItems[0].contentItems[1].element.hide(); 
myLayout.updateSize()

//or we can add child to the layout

let newConfig={..}
event.root.contentItems[0].contentItems[0].addChild(newConfig); 

```
Please let me know how to achieve the same in angular.

**Comment by martin31821** [comment]
Should be possible to inject using a custom injection token, just like you get the component state.
There's a large rewrite in progres with a full API redesign and a much cleaner API, so this will go in there definitely.

**Comment by shobanmr** [comment]
> Should be possible to inject using a custom injection token, just like you get the component state.
> There's a large rewrite in progres with a full API redesign and a much cleaner API, so this will go in there definitely.

If it is already done please share the API documentation link, if not when can i expect ?

**Comment by martin31821** [comment]
If you require this feature, feel free to prepare a PR against the NG 8-electron branch (rewrite from scratch).

Otherwise, I think the rewrite will be done in something like 4 to 6 weeks, depending on my time

**Comment by martin31821** [comment]
As of 0.0.16, it's possible to inject the GoldenLayoutEventHub to your component and get a reference to the event hub.

**Comment by shobanmr** [comment]
@martin31821 I couldn't find 0.0.16 version in 

> https://www.npmjs.com/package/@embedded-enterprises/ng6-golden-layout
Will you share me the updated npm package link
