### ISSUE TITLE
Creating New Windows or Tabs

### ISSUE THREAD

**Issue by shobanmr** [EmbeddedEnterprises/ng6-golden-layout#24]
Can we able to add new component into goldenlayout configuration dynamically ?
like ...
` var newItemConfig = {`
       ` title: title,`
        `type: 'component',`
       ` componentName: 'example',`
       ` componentState: { text: text }`
   ` };`
 `myLayout.selectedItem.addChild( newItemConfig );`

**Comment by martin31821** [comment]
In the angular 6 version it can be done using the GoldenLayoutService.
In the new angular 8 version, you can inject a reference to the LayoutManager and use its API directly.

**Comment by shobanmr** [comment]
Can you please provide me a sample code for it.

**Comment by martin31821** [comment]
Find sample code for the ng8 branch here: https://github.com/EmbeddedEnterprises/ngx-golden-layout-electron/blob/master/src/app/components.ts
Find sample code for the ng6 branch here: https://github.com/EmbeddedEnterprises/ng6-golden-layout/blob/master/src/app/app.module.ts#L41

Note that the ng6 branch is not maintained actively, development takes place at the ng8 version and you're strongly advised to update.

**Comment by shobanmr** [comment]
![Screenshot from 2019-08-06 18-34-47](https://user-images.githubusercontent.com/37335034/62542195-efc8a080-b878-11e9-83ac-d6d40062fe36.png)

By default the tab(testing) is getting added in first window can we able to add tabs in a particular window such as In the above picture there are 6 windows can we able mention that the tab needs to be added in a particular window

**Comment by martin31821** [comment]
Hmm, The golden-layout API is able to do this, but the `createNewComponent` function can't. Maybe we should add a callback to modify the layout tree.

**Comment by Abdullah0991** [comment]
> Hmm, The golden-layout API is able to do this

How? can you provide an example?

I tried the following but not succeeded:
```
constructor(@Inject(GoldenLayoutContainer) private container: GoldenLayout.Container) {}

this.container.parent.addChild({
  componentName: 'chart',
  type: 'component'
});
```

**Comment by martin31821** [comment]
I'd propose the API to look like this:
```
this.host.createNewComponent({
  type: 'component',
  componentName: componentName,
  title: 'Title ',
}, selector: ((item: GoldenLayout.Item) => boolean = null));
```
Where selector will be called for each item in the hierarchy and if it returns true, the component will be attached to this item.

@mrshoban27 WDYT?

**Comment by pbklink** [comment]
Maybe add an option to add the new component under a new stack attached to the selected item.

I would use this option when adding the first component in a golden layout to determine whether it is shown as tab or without a tab.
