### ISSUE TITLE
Error: Cannot read property 'has' of undefined.

### ISSUE THREAD

**Issue by sagunpandey** [EmbeddedEnterprises/ng6-golden-layout#25]
I am getting this error:

`Cannot read property 'has' of undefined.`

![screenshot](https://user-images.githubusercontent.com/3306020/62875157-83262980-bcf0-11e9-8962-91eef438b747.png)

The error is coming out from ngx-golden-layout.js -> MultiWindowService() function. For some reason rootWindow.__ServiceConstructors is undefined. I did try creating a MultiWindowService and adding it to the module. What is it that I am doing wrong?

**Comment by martin31821** [comment]
Did you call `MultiWindowInit()` **BEFORE** bootstrapping your angular app (i.e. in `main.ts`)?

**Comment by sagunpandey** [comment]
@martin31821 That was it. Thank you so much.
