### ISSUE TITLE
NullInjectorError

### ISSUE THREAD

**Issue by Abdullah0991** [EmbeddedEnterprises/ng6-golden-layout#27]
Hi,

I am using ngx-golden-layout@0.0.18 with angular 8.2.2, everything thing is worked well, but when I try to 'Accessing the underlying GoldenLayout API' using the example in the ReadMe I got the error:

> Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(AppModule)[AdminLayoutComponent -> function( config, container ) {]: 
>   StaticInjectorError(Platform: core)[AdminLayoutComponent -> function( config, container ) {]: 
>     NullInjectorError: No provider for function( config, container ) {!
> NullInjectorError: StaticInjectorError(AppModule)[AdminLayoutComponent -> function( config, container ) {]: 
>   StaticInjectorError(Platform: core)[AdminLayoutComponent -> function( config, container ) {]: 
>     NullInjectorError: No provider for function( config, container )

My app have appModule and sharedModule, In appModule I import like this: `GoldenLayoutModule.forRoot(componentTypes)`

And in sharedModule like this: `GoldenLayoutModule`.

I don't know how to solve this! any help will be appriciated :)

**Comment by Abdullah0991** [comment]
Also tried what you said in this issue: https://github.com/EmbeddedEnterprises/ng6-golden-layout/issues/24#issuecomment-518645820

Same error.

**Comment by OuttaLineNomad** [comment]
I get a similar error with Angular 7 ng6-golden-layout 0.0.12. I can't find a way to access the Golden Layout API.

**Comment by martin31821** [comment]
Fixed in 0.0.20, please be aware that the API changed a bit, due to popout/popin issues.

**Comment by Abdullah0991** [comment]
Hi, 
I updated to 0.0.20 and use the new example in the readme.md but nothing change, same error:

> Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(AppModule)[AdminLayoutComponent -> InjectionToken GoldenLayoutComponentHost]: 
>   StaticInjectorError(Platform: core)[AdminLayoutComponent -> InjectionToken GoldenLayoutComponentHost]: 
>     NullInjectorError: No provider for InjectionToken GoldenLayoutComponentHost!
> NullInjectorError: StaticInjectorError(AppModule)[AdminLayoutComponent -> InjectionToken GoldenLayoutComponentHost]: 
>   StaticInjectorError(Platform: core)[AdminLayoutComponent -> InjectionToken GoldenLayoutComponentHost]: 
>     NullInjectorError: No provider for InjectionToken GoldenLayoutComponentHost!

Here is the code:
```
import { GoldenLayoutComponent, GoldenLayoutComponentHost, GoldenLayoutContainer } from 'ngx-golden-layout';
@Component({})
constructor(@Inject(GoldenLayoutComponentHost) private goldenLayout: GoldenLayoutComponent,
@Inject(GoldenLayoutContainer) private container: GoldenLayout.Container)
{}
```

Thanks.

**Comment by martin31821** [comment]
@Abdullah0991 just to be sure that this is actually valid, the component you're describing here is a component which is spawned **within** golden-layout?

**Comment by Abdullah0991** [comment]
No, it's the parent component in-which golden-layout will spawn in.

**Comment by martin31821** [comment]
Okay, for the parent component, just use a ViewChild as documented here: https://github.com/EmbeddedEnterprises/ng6-golden-layout/blob/cf3ef9acd147ea3d947bf53f1681ed6391f6969b/src/app/app.module.ts#L90

The GoldenLayoutComponentHost and other tokens are only available for components which are rendered as children from golden-layout.
