### ISSUE TITLE
Set Active Tab Method

### ISSUE THREAD

**Issue by OuttaLineNomad** [EmbeddedEnterprises/ng6-golden-layout#28]
Can we activate a tab that is already created? As if the user clicked on the tab? I know there is create a tab in `GoldenLayoutService` but I don't see a way to activate an already created tab. 

like 
```
this.goldenLayoutService.setActive(item)
```

**Comment by martin31821** [comment]
You can use the goldenlayout API to set the active tab, see #27, which is fixed in 0.0.20.
