### ISSUE TITLE
stateChanged always emits undefined

### ISSUE THREAD

**Issue by Abdullah0991** [EmbeddedEnterprises/ng6-golden-layout#29]
Hi,

I am using ngx-golden-layout@0.0.20 with Angular 8.2.2, using the `stateChanged` event always returns an undefined value.

`<golden-layout-root [layout]="layoutConfig" (stateChanged)="layoutChanged($event)"></golden-layout-root>`

In component:
```
INITIAL_LAYOUT: GoldenLayout.Config = {...};
layoutConfig = of(this.INITIAL_LAYOUT);

layoutChanged(evt: any) {
  console.error('Layout changed', evt);
}
```

**Comment by martin31821** [comment]
This is by design, see the golden-layout website (quote below).

> You might wonder why you have to call myLayout.toConfig() explicitly rather than just getting the new state as a parameter of the stateChanged callback. This is because serialisinging entire layouts can be expensive - and stateChanged will fire a lot. It might therefor be a good idea to 'debounce' your state save calls or offer a save-button, depending on your performance requirements.
