### ISSUE TITLE
Name of tab

### ISSUE THREAD

**Issue by Julianhm9612** [EmbeddedEnterprises/ng6-golden-layout#3]
How can i set name of the tab?

**Comment by martin31821** [comment]
You can set the tab title using the default golden-layout config: http://golden-layout.com/docs/ItemConfig.html

Please close the issue if it works for you.

**Comment by Julianhm9612** [comment]
Can I put a name when creating a new tab?

Example in this line:

![image](https://user-images.githubusercontent.com/24255842/45956075-44ec2280-bfd7-11e8-85a3-849e1fedcdae.png)

This ComponentName is the selector of the component, but i need put a name:

![image](https://user-images.githubusercontent.com/24255842/45956217-9c8a8e00-bfd7-11e8-9b9c-b600b99626c1.png)

**Comment by martin31821** [comment]
Maybe it's possible to extend the interface to create a new component, I have to check the golden-layout documentation for this...

I'll keep it open as feature request.

**Comment by martin31821** [comment]
Tab name can be set injecting the GoldenLayout container, as described in https://github.com/EmbeddedEnterprises/ng6-golden-layout/pull/12. 

I'm closing this as resolved.
