### ISSUE TITLE
Inner layout inside the main layout

### ISSUE THREAD

**Issue by Abdullah0991** [EmbeddedEnterprises/ng6-golden-layout#30]
Hi,

Using ngx-golden-layout@0.0.20 with Angular 8.2.2, I want to add an inner layout inside a component which is lay inside a panel of the main layout.

I tried, but it throw an error:

> ERROR RangeError: Maximum call stack size exceeded
>     at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:147)
>     at NgZone.push../node_modules/@angular/core/fesm5/core.js.NgZone.run (core.js:26169)
>     at _loop_1 (ngx-golden-layout.js:860)
>     at ApplicationRef.__tick (ngx-golden-layout.js:868)
>     at ngx-golden-layout.js:863
>     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:391)
>     at Object.onInvoke (core.js:26255)
>     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:390)
>     at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:150)
>     at NgZone.push../node_modules/@angular/core/fesm5/core.js.NgZone.run (core.js:26169)
> 

I don't put any children in the inner layout, just do this:
`<golden-layout-root [layout]="layoutConfig"></golden-layout-root>`
inside the component's template.

And the code is:
`layoutConfig = of({ content: [] });`

Any suggestions ?

**Comment by martin31821** [comment]
Fixed in 83fbd30
