### ISSUE TITLE
Cannot add 2nd component after deleting all components

### ISSUE THREAD

**Issue by pbklink** [EmbeddedEnterprises/ng6-golden-layout#34]
If you delete all components in a Golden Layout and then try to add new ones using GoldenLayoutComponent.createNewComponent(), the first one will work, but the second one will not.

Looks like the first one works because `element` is set to root as there are zero contentItems.

The second one fails because
`element = this.findStack(root.contentItems);`
cannot find a stack and sets element to undefined.

**Comment by martin31821** [comment]
Got it reproduced, will fix asap together with #24.
