### ISSUE TITLE
BUG: ContentItem deleted after its content get changed

### ISSUE THREAD

**Issue by Abdullah0991** [EmbeddedEnterprises/ng6-golden-layout#38]
Hi,

Having a layout like this:
```
{
  content: [{
    type: 'row',
    content: [{
      type: 'column',
      id: 'first-col',
      content: [{
        type: 'component',
        componentName: 'first-component'
      }, {
        type: 'column',
        id: 'sec-col',
        content: [{
          type: 'component',
          componentName: 'second-component'
        }]
      }]
    }]
  }]
}
```

When I want (for example) to add a new component to second column (bellow the second component), I use:
```
const secCol = this.goldenLayout.getGoldenLayoutInstance().root.getItemsById('sec-col');
secCol[0].addChild({...});
```

The above code is always working for first time, in second time, if I close one of the components in `sec-col`, and tried the above code, `sec-col` will not be found.
It will be deleted from the layout and it's content will be added to its parent content-item (as I found in the investigation).

ngx-golden-layout : 0.0.22;
golden-layout : 1.5.9

**Comment by Abdullah0991** [comment]
@martin31821 Any updates on this?

**Comment by martin31821** [comment]
You have a Column as child of another column, which causes it to be collapsed on the next golden-layout reflow.
You should use something like this:
```
{
  content: [{
    type: 'row',
    content: [{
      type: 'column',
      id: 'first-col',
      content: [{
        type: 'component',
        componentName: 'first-component'
      }, {
          type: 'component',
          componentName: 'second-component'
        }]
      },{
      type: 'column',
      id: 'sec-col',
      content: [{
        type: 'component',
        componentName: 'third-component'
      }, {
          type: 'component',
          componentName: 'fourth-component'
        }]
      }]
    }]
  }]
}
```
So I don't think this is a problem related to my code. 
If the issue persists, please open an issue in the golden-layout code.

**Comment by Abdullah0991** [comment]
> So I don't think this is a problem related to my code.
> If the issue persists, please open an issue in the golden-layout code.
> 

You'r right, it seems a bug in golden-layout, here is the issue link:
https://github.com/golden-layout/golden-layout/issues/544
