### ISSUE TITLE
Feature Request: Support RTL

### ISSUE THREAD

**Issue by Abdullah0991** [EmbeddedEnterprises/ng6-golden-layout#43]
Hi,

Can you please add an option to `GoldenLayout.Config` to support RTL, means the GL content float from right to left.
 
I tried set `dir='rtl'` on the parent but it only make the tabs float from right, I want to float the contents also from right to left.

**Comment by martin31821** [comment]
This is out of scope for the angular wrapper, please reopen an issue in goldenlayout itself.
