### ISSUE TITLE
Unable to replaceChild with registered component

### ISSUE THREAD

**Issue by Glamurio** [EmbeddedEnterprises/ng6-golden-layout#44]
Hey, I'm trying to work my way around GoldenLayout and have hit a bit of a dead-end. I've tried many variations, but for some reason I just cannot seem to be able to replace the child of a component that I've registered after serving the application.

Here's my current code:

```ts
import { Component, OnInit, Inject } from '@angular/core';

import * as GoldenLayout from 'golden-layout';
import { GoldenLayoutContainer, GoldenLayoutComponentHost, GoldenLayoutComponent } from 'ngx-golden-layout';

@Component({
  selector: 'app-subscriptions',
  templateUrl: './subscriptions.component.html',
  styleUrls: ['./subscriptions.component.scss']
})
export class SubscriptionsComponent implements OnInit {

  public newConfig: GoldenLayout.ItemConfig = {
    type: 'column',
    content: [{
      type: 'component',
      id: 'Display',
      componentName: 'Display', // The name defined in componentTypes
      title: 'Display',
      isClosable: false
    }]
  };

  constructor(
    public services: Services,
    @Inject(GoldenLayoutComponentHost) private goldenLayout: GoldenLayoutComponent,
    @Inject(GoldenLayoutContainer) private container: GoldenLayout.Container
  ) {
    var GLI = this.goldenLayout.getGoldenLayoutInstance()
    var secCol = GLI.root.getItemsById('second-col')[0]

    GLI.registerComponent('Display', this.newConfig)
    var displayItem = GLI.root.getItemsById('Display')[0]

    secCol.parent.replaceChild(secCol, displayItem)

   }

  ngOnInit() {
  }
}
```

And unfortunately, this results in the following error:
`ERROR Error: "Uncaught (in promise): Error: Please register a constructor function`

I'd like to address that I've never really used GoldenLayout before and I'm still a beginner when it comes to Angular 8, so this is likely just my fault for misunderstanding something.

**Comment by martin31821** [comment]
You should not use registerComponent at this time, I think your code should look like this:
```ts
const GLI = this.goldenLayout.getGoldenLayoutInstance();
const secCol = GLI.root.getItemsById('second-col')[0];
secCol.parent.replaceChild(secCol, this.newConfig);
```

Which should replace it.

**Comment by Glamurio** [comment]
Thanks for the quick response! Unfortunately, I've already tried that before, it results in the following error:

`Error: "Uncaught (in promise): TypeError: newChild.config is undefined`

Any ideas?

Edit: I should mention. It _does_ replace the child accordingly, however the error still happens and I'd assumed that having random errors occur is something I should avoid.

**Comment by martin31821** [comment]
Can you post the complete stack trace? I'm trying to guess where that error originates, but I don't see anything

**Comment by Glamurio** [comment]
Sure, yeah, here's the full stack trace:

```
ERROR TypeError: "newChild.config is undefined"
    replaceChild vendor-es2015.js:102517
    changeChild main-es2015.js:1046
    View_NewsComponent_2 NewsComponent.html:3
    handleEvent vendor-es2015.js:75765
    callWithDebugContext vendor-es2015.js:77383
    debugHandleEvent vendor-es2015.js:77019
    dispatchEvent vendor-es2015.js:63485
    renderEventHandlerClosure vendor-es2015.js:74697
    decoratePreventDefault vendor-es2015.js:88304
    invokeTask polyfills-es2015.js:3397
    onInvokeTask vendor-es2015.js:71849
    invokeTask polyfills-es2015.js:3396
    runTask polyfills-es2015.js:3174
    invokeTask polyfills-es2015.js:3471
    invokeTask polyfills-es2015.js:4609
    globalZoneAwareCallback polyfills-es2015.js:4635
```
I call the `replaceChild()` function in a `changeChild()` function, but otherwise nothing's changed, and the error happened before the change as well.

**Comment by martin31821** [comment]
unfortunately, this is not very helpful... could you also include the source code at `vendor-es2015.js:102517`?

**Comment by Glamurio** [comment]
Ah, sorry, I should have had the foresight to include it. I've also mixed up the stack trace I receive on the `ng build` version, here's the stack trace on `localhost`:

```
ERROR TypeError: "newChild.config is undefined"
    replaceChild goldenlayout.js:3987
    changeChild news.component.ts:38
    View_NewsComponent_2 NewsComponent.html:3
    Angular 13
        handleEvent
        callWithDebugContext
        debugHandleEvent
        dispatchEvent
        renderEventHandlerClosure
        decoratePreventDefault
        invokeTask
        onInvokeTask
        invokeTask
        runTask
        invokeTask
        invokeTask
        globalZoneAwareCallback
```
And here's `goldenLayout.js:3987` (which is equivalent to `vendor-es2015.js:102517`), on the off-chance you can't easily access it:
```

	replaceChild: function( oldChild, newChild ) {
		var size = oldChild.config[ this._dimension ];
		lm.items.AbstractContentItem.prototype.replaceChild.call( this, oldChild, newChild );
		newChild.config[ this._dimension ] = size;
		this.callDownwards( 'setSize' );
		this.emitBubblingEvent( 'stateChanged' );
	},
```

Seems to me the problem is caused by the fact that `oldChild.config[this._dimension]` returns undefined.

**Comment by Glamurio** [comment]
Good news! I had some time, tested a bit, and figured out the problem.
`replaceChild()` expects either a `GoldenLayout.ContentItem` or a `GoldenLayout.ItemConfigType`.

So far so good, but the JS code is actually only prepared to handle `ContentItem`. `newChild.config` does not exist in `ItemConfig`, because it's already a config. I've gone ahead and amended the code, I'm unsure if this is the most optimal way to handle it, but it works at least.

```
	replaceChild: function( oldChild, newChild ) {
		var size = oldChild.config[ this._dimension ];
		lm.items.AbstractContentItem.prototype.replaceChild.call( this, oldChild, newChild );
		if (!newChild.config) {
			newChild[ this._dimension ] = size;
		} else {
			newChild.config[ this._dimension ] = size;
		}
		this.callDownwards( 'setSize' );
		this.emitBubblingEvent( 'stateChanged' );
	},
```

As you can see, I'm merely checking if a config exists, and if it doesn't, it will assume that the item itself is already a config.

Of course this only fixes the issue in the JS, if you want to change this for others you'll have to amend the TS itself. I suggest implementing a user-defined type guard, something like this:

```
  isItemConfig(itemConfig: any): itemConfig is GoldenLayout.ItemConfigType {
      return itemConfig.id !== undefined;
  }
```
This way you're able to evaluate whether or not it's a config.

**Comment by martin31821** [comment]
Unfortunately, this is something I can't fix in this library but it needs to be fixed within golden-layout itself. I'd suggest to close this bug and open a new one in golden-layout to track this issue, maybe with a more descriptive title like `replaceChild not working for itemConfigs`.
