### ISSUE TITLE
Proper way to capture ContentItem maximize/minimize events

### ISSUE THREAD

**Issue by Abdullah0991** [EmbeddedEnterprises/ng6-golden-layout#45]
Hello,
What is the proper way to capture the `ContentItem` maximize/minimize events ?

**Comment by martin31821** [comment]
You should be able to inject the parent and listen to its maximised/minimised events.

**Comment by Abdullah0991** [comment]
I looked in the [documentations](http://golden-layout.com/docs/Container.html#Events), there is no events for `maximize/minimize` events.

Could you please give me the events names ?

And why the `maximizing/minimizing` actions not fire the `resize` event also ?

**Comment by martin31821** [comment]
I just checked within the source code, it's `minimise` and `maximise` and these events are emitted on the content item.

**Comment by Abdullah0991** [comment]
Hi, I tried like this but not worked:

```
constructor(@Inject(GoldenLayoutContainer) private container: GoldenLayout.Container) {
    this.container.tab.contentItem.on('maximise', () => { // Do Something });
    this.container.tab.contentItem.on('minimise', () => { // Do Something });
}
```

**Comment by Abdullah0991** [comment]
up!

**Comment by Abdullah0991** [comment]
up!!

**Comment by Abdullah0991** [comment]
> I just checked within the source code, it's `minimise` and `maximise` and these events are emitted on the content item.

Can you confirm this works ? I haven't found a solution yet.

**Comment by martin31821** [comment]
```ts
constructor(@Inject(GoldenLayoutContainer) private container: GoldenLayout.Container) {
    this.container.parent.parent.on('maximised', () => { // Do Something });
    this.container.parent.parent.on('minimised', () => { // Do Something });
}
```
