### ISSUE TITLE
@MultiWindowService works in dev build but not in prod mode

### ISSUE THREAD

**Issue by sagunpandey** [EmbeddedEnterprises/ng6-golden-layout#46]
Hi, I am building a detachable/dockable admin panel using Golden Layout. My app requires detaches panel to communicate with the main app, and to achieve that I have been using @MultiWindowService. Everything works just fine in the dev build but undefined is injected for services while using in prod build. Is this a bug?

**Comment by sagunpandey** [comment]
Maybe related to #41

**Comment by martin31821** [comment]
I think you're hitting a different bug than #41. Please include:
- output of `ng version`
- `angular.json`
- all of your `tsconfig-*.json`

If possible, a minimal reproduction fo this bug.

**Comment by sagunpandey** [comment]
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect                 0.802.1
@angular-devkit/build-angular         0.802.1
@angular-devkit/build-optimizer      0.802.1
@angular-devkit/build-webpack       0.802.1
@angular-devkit/core                        8.2.1
@angular-devkit/schematics             8.2.1
@angular/cdk                                    8.1.2
@angular/compiler                           8.2.10
@angular/material                            8.1.2
@ngtools/webpack                           8.2.1
@schematics/angular                        8.2.1
@schematics/update                        0.802.1
rxjs                                                    6.5.2
typescript                                         3.5.3
webpack                                          4.38.0




[angular.json.txt](https://github.com/EmbeddedEnterprises/ng6-golden-layout/files/3768217/angular.json.txt)

[tsconfig.app.json.txt](https://github.com/EmbeddedEnterprises/ng6-golden-layout/files/3768225/tsconfig.app.json.txt)

[tsconfig.json.txt](https://github.com/EmbeddedEnterprises/ng6-golden-layout/files/3768223/tsconfig.json.txt)

**Comment by sagunpandey** [comment]
```
@MultiWindowService<MultiWindowSelectionService>()
@Injectable()
export class MultiWindowSelectionService {

  private _currentDocumentId$ = new BehaviorSubject<number>(null);

  get currentDocumentId() {
    return this._currentDocumentId$;
  }

  set setCurrentDocumentId(currentDocumentId: number) {
    this._currentDocumentId$.next(currentDocumentId);
  }
}
```

As we can, this is my use case. One of my windows will update the subject and the other will listen to the change. However, `currentDocumentId()` returns undefined where it should have returned the BehaviorSubject. This is just a minified example, all other properties or injected services are undefined.

If my implementation was the issue it shouldn't have worked in dev build as well. Any ideas @martin31821 ?

**Comment by martin31821** [comment]
It seems that constructor.name is undefined in angular production builds, therefore I need to do a breaking API change to `MultiWindowService`.

This will fix two problems: 
- Undefined in child windows in production build
- You can't have two identical named Services at the moment.

The change will look like this: 
`MultiWindowService(uniqueIdentifier)` which will be used instead of the current signature.

**Comment by sagunpandey** [comment]
@martin31821 Thank you so much for deducing the cause of the issue. May I ask when should I expect the change to be live? I am meeting deadlines, so I might have to go for some other temporary solutions (like using `localstorage `to synchronize instead of `MultiWindowService`). Thank you again.

**Comment by martin31821** [comment]
Should be fixed in the latest release

**Comment by sagunpandey** [comment]
@martin31821 I am testing right now, I will update the ticket accordingly. Thank you so much for your kind efforts.

**Comment by sagunpandey** [comment]
Everything works perfectly. Kudos to you.
