### ISSUE TITLE
How to configure docked components with Input/Output

### ISSUE THREAD

**Issue by bking-gh** [EmbeddedEnterprises/ng6-golden-layout#49]
Hi using the ngx-golden-layout-electron example was able to get basic docking set up for my custom components. But what if your components have input/output, normally configured in the template with [myinput]="data" etc.  Where in the configuration can this be set up? Thanks

**Comment by martin31821** [comment]
I think this would impose severe problems when trying to serialize layouts etc. 
Basically, how would you describe something like a bound output, within the layout state?
I can't be sure that even the code to be executed will exist lateron.

Therefore the decision was made to let all components communicate via services exclusively.

If you have a good idea how the API should look like and behave, I could look into it, but for now, it's a wontfix.

**Comment by bking-gh** [comment]
Thanks will look into the service method...
