### ISSUE TITLE
Components not created with Angular 9

### ISSUE THREAD

**Issue by pbklink** [EmbeddedEnterprises/ng6-golden-layout#53]
Hi,
Just tried to update my application to Angular 9.
None of my Angular components are created by Golden Layout.  Console shows "Resolving component \<Component Name\>", but constructor for \<Component  Name\> is not called.

Traced it through to goldenLayout.createContentItem(myConfig) and things seemed ok, but then it becomes difficult due to promises (I think).

Should ngx-golden-layout work with Angular 9?  If so, any hints as to how I can investigate my problem further?

Thanks, Paul

**Comment by martin31821** [comment]
I didn't had the time to look into angular  9 yet, so we're fixed at 8.

I can imagine it's related to ivy.

**Comment by martin31821** [comment]
@pbklink I just updated my electron testbed to angular 9 and it works fine, so there must be something within your specific app.

https://github.com/EmbeddedEnterprises/ngx-golden-layout-electron

**Comment by pbklink** [comment]
@martin31821 thanks.  Will investigate further next weekend and report back if I figure anything out.

**Comment by martin31821** [comment]
When the component constructor is not called, it sounds to me like a mismatched plugin configuration or a spelling error. Are you using ivy or viewEngine? Otherwise, please post a project to reproduce on codepen or in a repo.

**Comment by pbklink** [comment]
Found the problem.

Previously app.module.ts was structured with `ComponentType[]` in a namespace at the end.

```
@NgModule({
    declarations: [
       ...
    ],
    imports: [
        ...
        GoldenLayoutModule.forRoot(AppModule.goldenLayoutComponentTypes),
    ],
    providers: [
       ...
    ],
    bootstrap: [AppComponent]
})

export class AppModule {
    ...
}

export namespace AppModule {
    export const goldenLayoutComponentTypes: ComponentType[] = [
        {
            name: ItemType.idToName(ItemTypeId.Component1),
            type: Component1,
        },
        ...
    ];
}
```

I moved the `ComponentType[]` array out of the namespace and into module scope and then GoldenLayout started working.

```
const goldenLayoutComponentTypes: ComponentType[] = [
    {
        name: ItemType.idToName(ItemTypeId.Component1),
        type: Component1,
    },
    ...
];

@NgModule({
    declarations: [
       ...
    ],
    imports: [
        ...
        GoldenLayoutModule.forRoot(goldenLayoutComponentTypes),
    ],
    providers: [
       ...
    ],
    bootstrap: [AppComponent]
})

export class AppModule {
    ...
}
```

Not sure why this made a difference.  I am somewhat new to Angular (having come from Delphi) and am still working out my patterns.

Thanks for your assistance.

**Comment by martin31821** [comment]
This is because the decorators run before the field is actually initialized, which is required for the decorator to get the component types.
You could also register your component types dynamically using the ComponentRegistryService, but that's a fairly advanced use case.
