### ISSUE TITLE
Support for hide panels

### ISSUE THREAD

**Issue by vmcbaptista** [EmbeddedEnterprises/ng6-golden-layout#59]
Hi all.
First of all congrats for all your effort in supporting an Angular version for Golden Layout.

I'm wondering if we can have panels like VS. I see that this was addressed in the main project but seems a bit abandoned.

https://github.com/golden-layout/golden-layout/pull/268

Does this library support this? And if so, can you help me with an example?

Thanks.

**Comment by martin31821** [comment]
I can only support features from upstream. However, your help would be appreciated bringing the mentioned PR in shape and I'm happy to merge PRs.
