### ISSUE TITLE
MultiWindowService breaks services when building with optimization=true

### ISSUE THREAD

**Issue by ArulRozario** [EmbeddedEnterprises/ng6-golden-layout#61]
When decorating a service with @MultiwindowService, all methods and properties of the service get removed when building with optimization=true. If it set to false, everything works fine. Obviously it's not production ready as the bundle size is huge when optimization = false. 

Here is my angular.json build configuration
`"optimization": true,
              "outputHashing": "all",
              "sourceMap": true,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "20mb",
                  "maximumError": "20mb"
                }
              ]`
tsconfig.json
`"compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es5",
    "resolveJsonModule": true,
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ],`

package.json

`   
  "@angular/core": "^8.2.14",
 "golden-layout": "^1.5.9",
 "ngx-golden-layout": "0.0.20",

`

**Comment by martin31821** [comment]
Please update to the latest version of both angular and this package, as there was a fix for the production build in 0.0.25 (https://github.com/EmbeddedEnterprises/ng6-golden-layout/commit/cda935ca3230b67608dc274121e3e399bb28f1fa).

If the issue persists, feel free to reopen this issue.
