### ISSUE TITLE
Could make a service that used underlying GoldenLayout API?

### ISSUE THREAD

**Issue by OuttaLineNomad** [EmbeddedEnterprises/ng6-golden-layout#63]
I have created my own GoldenLayout component that I have used for months, but now I am getting a golden layout error that ng6-golden-layout has seemed to fix. Also, this is a great package, so I would like to use it in my project. The problem is I have calls to my GoldenLayout component all over my project, to custom methods I created to work with the GL API the way I needed it. Now If I use ng6-golden-layout I will lose those custom methods. This is due to the way it interact with the underlying API, I see I would reach the api in each component. Is there a way to use the API in a service, that I store my custom methods? So, the methods I have now could still work with ng-golden-layout.

**Comment by martin31821** [comment]
You can access the gl api like described in the Readme under 'accessing the golden layout API'.

Otherwise, I'd also like to merge a PR extending the golden layout service!

**Comment by martin31821** [comment]
I think I misunderstood your original question, sorry.

To use the API in a service, you should pass the reference to your goldenlayout component into your service upon creation and use it from there, that's the closest you can get.
You can also inject the GoldenLayoutComponentHost token in any component within the GoldenLayout container.

**Comment by OuttaLineNomad** [comment]
Thanks, yes that is what I was asking.
