### ISSUE TITLE
MultiWindowService Error when pdoruction in local continaer

### ISSUE THREAD

**Issue by morisamon** [EmbeddedEnterprises/ng6-golden-layout#68]
Hey,
I use the ngx-golden-layout": "0.0.17 version in Angular 8
The MultiWindowService directive works well when I run the code from the development environment from visual code.
But, when I build a prod and run it in the local container I receive an error from PluginRegistryService

![image](https://user-images.githubusercontent.com/21128206/88173269-f5a2c780-cc2a-11ea-95da-9fec839fa1cd.png)

![image](https://user-images.githubusercontent.com/21128206/88173386-284cc000-cc2b-11ea-82d1-9c7573641d5c.png)

May you help me, please?

**Comment by martin31821** [comment]
Please update to the latest version, 0.0.17 won't get any bugfixes (sorry for that)
You might want to give the 0.0.37 a try, as well as 0.0.34 (if you're bound to angular 8 and the 0.0.37 does not work for you)

**Comment by morisamon** [comment]
Thank, it works =]
