### ISSUE TITLE
Dynamically rearrange tabs 

### ISSUE THREAD

**Issue by allanm852** [EmbeddedEnterprises/ng6-golden-layout#69]
Is there a dynamic way to rearrange tabs without refreshing golden layout or the components? Let say you load new config when you click a button or something.

**Comment by martin31821** [comment]
There is no such way without rearranging the component, also this is an NP hard (and possibly, not even solvable) problem.

You would need to use the API to calculate a diff, rearrange panels to match the new layout, open new panels, close old ones and update the state.

By updating the state, there is no guarantee that all panels will also accept state changes, which makes it impossible for me to implement this.

If you'd like to contribute a solution, feel free to open a PR in the golden-layout repo :)
