### ISSUE TITLE
Opening golden layout application from another app

### ISSUE THREAD

**Issue by morisamon** [EmbeddedEnterprises/ng6-golden-layout#71]
Our group has developed an app with a golden layout.
Another team added a link/button to another app that opens our app in a new tab/window.
They get a cross-origin frame error when they move to a screen that contains the golden layout.
If the team opens our application on the same page - it works.
We notice there is a problem with MultiWindowService, please find the attachment:

![image](https://user-images.githubusercontent.com/21128206/96361876-0089cd00-1132-11eb-894f-0652e0fba5ad.png)

"@angular/core": "^8.2.14"
"ngx-golden-layout": "0.0.31"

Can you help us, please?

**Comment by dishubagga** [comment]
Hi morisamondid you find solution for this?

**Comment by martin31821** [comment]
these issues should actually not appear anymore since this commit: https://github.com/EmbeddedEnterprises/ng6-golden-layout/commit/5f74804035377d92ed196de37b280a0b638c1531, where I fixed the invalid access to rootWindow.
