### ISSUE TITLE
Update Angular Dependency

### ISSUE THREAD

**Issue by mcdenhoed** [EmbeddedEnterprises/ng6-golden-layout#72]
Angular 11 is now out. I tried migrating an app using ngx-golden-layout and I got the following error:

```
                  Package "ngx-golden-layout" has an incompatible peer dependency to "@angular/common" (requires "^9.0.0" (extended), would install "11.0.0").
                  Package "ngx-golden-layout" has an incompatible peer dependency to "@angular/core" (requires "^9.0.0" (extended), would install "11.0.0").
```

Would it be possible to extend/update the angular dependency to allow usage with 11?

**Comment by martin31821** [comment]
I'll take a look once I updated our app to ng11.

Can you confirm that the binding works with angular 11?

**Comment by mcdenhoed** [comment]
Yeah, shortly after I posted this I forced the upgrade and it does seem to work. Been running them together for a few weeks now and haven't had any issues.

**Comment by martin31821** [comment]
Thanks for confirming, will update tomorrow.

**Comment by mCzolko** [comment]
Looking forward to tomorrow :D

**Comment by martin31821** [comment]
updated to ng13.

**Comment by mcdenhoed** [comment]
Thanks! And thanks for all the awesome work on GL proper!
