### ISSUE TITLE
To change the title in header dynamically

### ISSUE THREAD

**Issue by dishubagga** [EmbeddedEnterprises/ng6-golden-layout#74]
I am using ngx translate for example
content: [{
            type: 'row',
            content: [
            {
              type: 'component',
              componentName: 'side-bar', // The name defined in componentTypes
              title: this.translate.instant('side-bar'),
              width: 15,
              height: 40,
            }, {
              type: 'component',
              componentName: 'gridster', // The name defined in componentTypes
              title: this.translate.instant('gridster'),
              width: 90,
              height: 40,
            },
            ],
          }],
here in the title i want to change the title as the language changes but it does not change when the language changes. is there any possible way to solve this? for reference my code is 
import { Content } from '@angular/compiler/src/render3/r3_ast';
import { ChangeDetectorRef, OnInit, ViewChild, ɵConsole } from '@angular/core';
import { AfterViewInit } from '@angular/core';
import { Component } from '@angular/core';
import { NbThemeService } from '@nebular/theme';
import { TranslateService } from '@ngx-translate/core';
import { IExtendedGoldenLayoutConfig } from 'ngx-golden-layout';
import { Observable, of } from 'rxjs';

const INITIAL_LAYOUT: IExtendedGoldenLayoutConfig = {
    settings: {},
    dimensions: {
      borderWidth: 5,
      minItemHeight: 200,
      minItemWidth: 30,
      headerHeight: 24,
      dragProxyWidth: 50,
      dragProxyHeight: 50,
    },
    content: [{
      type: 'row',
      content: [
      {
        type: 'component',
        componentName: 'side-bar', // The name defined in componentTypes
        title: 'Sidebsddssar',
        width: 15,
        height: 40,
      }, {
        type: 'component',
        componentName: 'gridster', // The name defined in componentTypes
        title: 'Gridster',
        width: 90,
        height: 40,
      },
      ],
    }],
};

  @Component({
    selector: 'ngx-golden-layout',
    styleUrls: ['./golden-layout.layout.scss'],
    templateUrl: 'golden-layout.layout.html',
  })

  export class GoldenLayoutComponent implements OnInit, AfterViewInit {
    @ViewChild(GoldenLayoutComponent, { static: true }) layout: GoldenLayoutComponent;
    InitialLayout: IExtendedGoldenLayoutConfig;
    layoutConfig$: any;
    open_options_bar = false;
    themeSubscription: any;
    golden_layout_theme: any;

    getInitialLayout(): Observable<IExtendedGoldenLayoutConfig> {
      
        let initial_Layout = {
          settings: {},
          dimensions: {
            borderWidth: 5,
            minItemHeight: 200,
            minItemWidth: 30,
            headerHeight: 24,
            dragProxyWidth: 50,
            dragProxyHeight: 50,
          },
          content: [{
            type: 'row',
            content: [
            {
              type: 'component',
              componentName: 'side-bar', // The name defined in componentTypes
              title: this.translate.instant('side-bar'),
              width: 15,
              height: 40,
            }, {
              type: 'component',
              componentName: 'gridster', // The name defined in componentTypes
              title: this.translate.instant('gridster'),
              width: 90,
              height: 40,
            },
            ],
          }],
          
      }
      return new Observable(observer => {
        observer.next(initial_Layout);
      })

    }

    

    constructor(private theme: NbThemeService,
                private changeRef: ChangeDetectorRef,
                public translate: TranslateService,
                ) {
    }

    ngAfterViewInit(): void {
      this.themeSubscription = this.theme.getJsTheme().subscribe(config => {
        this.golden_layout_theme = 'golden-layout-' + config.name;
        this.changeRef.detectChanges();
      });
    }

    ngOnInit(): void {
      // this.getInitialLayout().subscribe((data) => {
      //   this.layoutConfig$ = of(data);
      // })
      this.layoutConfig$ = this.getInitialLayout();
      // this.setInitialLayout();
      // this.layoutConfig$ = of(this.InitialLayout);
      this.translate.onLangChange.subscribe(() => {
        console.log('language change');
       //  this.InitialLayout.content
        // this.setInitialLayout();
        // this.layoutConfig$ = of(this.InitialLayout);
      });

    }

    stateChanged(event: any): void {
      console.log('statechange');
    }

    showOptionsBar(): void {
      this.open_options_bar = !this.open_options_bar;
    }
}

**Comment by martin31821** [comment]
you can inject the Container into each dock panel as shown here:

https://github.com/EmbeddedEnterprises/ng6-golden-layout/blob/ng8-electron/src/app/app.module.ts#L165


Then you can call .setTitle(string) on this element.
