### ISSUE TITLE
Missing LICENSE files

### ISSUE THREAD

**Issue by aless2** [EmbeddedEnterprises/ng6-golden-layout#76]
There are no LICENSE files in the root folder and in projects/ngx-golden-layout.

projects/ngx-golden-layout/package.json file (copied below) states BSD-3-Clause as a license, but the LICENSE file itself is not available.

We would like to use ngx-golden-layout in a project that formally checks the intellectual property rights and missing LICENSE files could be a problem. 

Would it be possible to include the LICENSE files? 
Thanks.

{
  "name": "ngx-golden-layout",
  "version": "0.0.38",
  "license": "BSD-3-Clause",
  "author": {
    "name": "Martin Koppehel",
    "email": "mkoppehel@embedded.enterprises",
    "url": "https://embedded.enterprises"
  },
  "dependencies": {
    "tslib": "^2.0.0"
  },
  "peerDependencies": {
    "@angular/common": "^11.0.2",
    "@angular/core": "^11.0.2",
    "jquery": "3.5.1",
    "golden-layout": "1.5.9"
  }
}

**Comment by martin31821** [comment]
Of course, will include them in the next release.

**Comment by aless2** [comment]
Great. Thanks.
