### ISSUE TITLE
How can i create new window for the component? and when i use createNewComponent it adds new tab not new window!

### ISSUE THREAD

**Issue by dishubagga** [EmbeddedEnterprises/ng6-golden-layout#77]
settings: {},
  dimensions: {
    borderWidth: 5,
    minItemHeight: 200,
    minItemWidth: 30,
    headerHeight: 24,
    dragProxyWidth: 50,
    dragProxyHeight: 50,
  },
  content: [{
    type: 'row',
    content: [{
      type: 'row', 
      content: [{
                type: 'component',
                componentName: 'name', // The name defined in componentTypes
                title: 'Left',
                id: 'left',
                componentState: { text: 'Component root' },
                
              },
              {
                type: 'component',
                componentName: 'name', // The name defined in componentTypes
                title: 'Right',
                id: 'right',
                componentState: { text: 'Component root' },
                props: {text: 'hell oo'}
              }
            ]
    }]
  }],

  
  
};
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements GlOnResize{
  layoutConfig$ = new BehaviorSubject(INITIAL_LAYOUT);
  data: any;
  previousLeftId: string = 'left0';
  newId: number = 1;

  @ViewChild(GoldenLayoutComponent, { static: true }) layout: GoldenLayoutComponent;
  constructor(
    private registoryService: ComponentRegistryService,
    private tabService: TabService

  ) {
  }

  ngOnInit(){
    
    
  }

  ngAfterViewInit() {
    this.tabService.getTabsData().subscribe( (data) => {
      this.data = data.data;
      console.log(this.data.length);
      for(let i = 0; i < this.data.length; i++){
        console.log(this.data[i]);
        
        this.layout.createNewComponent({
          type: 'component',
          componentName: this.data[i].componentName,
          title:this.data[i].title,
          id: this.data[i].id,
          componentState: this.data[i].componentState,    
        }, this.data[i].idOfWindow)
      }

      this.layout.closeComponent('right');
      this.layout.closeComponent('left');

    });
    
    
  }
  glOnResize() {
    console.log('glOnResize');
    this.layout.beforeUnload()
    
  }

  stateChange() {
    console.log('State changed');
     //console.log('this.stateChange', this.layout.getSerializableState());
  }
  afterLoad() {
    console.log('on load');
  }
  tabActivated(tab) {
    console.log('hello on tab' + tab.config.componentState.text);
    if(tab.config.id != this.previousLeftId){
      this.layout.createNewComponent({
        type: 'component',
        componentName: 'name',
        title: 'from ' + tab.config.title,
        componentState: { text: 'got from ' + tab.config.componentState.text },
        id: String(this.newId),
      }, this.previousLeftId);
      this.layout.closeComponent(this.previousLeftId);
      this.previousLeftId = String(this.newId);
      this.newId = this.newId + 1;

    }

    
  }
  
}

**Comment by martin31821** [comment]
It's not possible to create a new window from the API right now.
