### ISSUE TITLE
Stable Version

### ISSUE THREAD

**Issue by shobanmr** [EmbeddedEnterprises/ng6-golden-layout#90]
@martin31821 Hi Martin,
I have used ngx-golden-layout V0.0.20 for 2 to 3 years in angular(v8) app. Can you tell which version will be stable for angular 8 application now?

**Comment by mcdenhoed** [comment]
I can't speak for @martin31821, but I have been tracking the latest versions of both ngx-golden-layout and angular in production (currently on 0.0.36 with angular 12) and have yet to run in to any compatibility issues between the two. I would suspect that you could successfully upgrade to the latest release, 0.0.36, with no problems.

I'm not sure what the plan for compatibility is with @martin31821's update for golden layout 2.

**Comment by martin31821** [comment]
The last version to support Angular 8 is 0.0.35. 
Anything newer might work but is not tested or supported.

Updates for golden-layout2 are planned, but I can't give a timeline as I'm very busy at the moment.

**Comment by shobanmr** [comment]
@mcdenhoed @martin31821 Thanks for the update.

**Comment by martin31821** [comment]
I released an intermediate version for angular 13 and updated deps, v0.0.39. 
GL2 is tracked in another issue.
