### ISSUE TITLE
Support Angular 14

### ISSUE THREAD

**Issue by johnthagen** [EmbeddedEnterprises/ng6-golden-layout#99]
[Angular 14 has been released](https://blog.angular.io/angular-v14-is-now-available-391a6db736af).

This package still targets Angular 13, so `npm` throws an error when trying to use Angular 14 with `ngx-golden-layout`:

https://github.com/EmbeddedEnterprises/ng6-golden-layout/blob/a9f5a446dd813cf6e25abe34866dd0ea092e9fc9/package.json#L14-L21

Could this package be updated for Angular 14 and a new release published?

**Comment by martin31821** [comment]
Can you try to run the installation with --legacy-peer-deps or --force and validate whether the library works for v14? 
I don't have the capacity to validate v14, but if someone can confirm that it works I'd update the dependencies and publish a new release.

**Comment by mcdenhoed** [comment]
Hey @martin31821 I've ported a medium-sized app using golden layout (though I don't use popout or maximization) to Angular 14 and it works great!

**Comment by johnthagen** [comment]
@martin31821 Yes the package works when installed with `--force`. A new NPM release would be great, thanks.

**Comment by johnthagen** [comment]
@martin31821 Checking back in to see if a new release could be published. Thanks.

**Comment by johnthagen** [comment]
@martin31821 Friendly ping to check in on if we could get a new release published.

**Comment by martin31821** [comment]
@johnthagen  Finally managed to publish a new update. Check out v0.0.40, should work with angular 14.
